# .streamlit/secrets.toml
#public_gsheets_url="https://docs.google.com/spreadsheets/d/11RbQnHSpGbmE7nzjerVF-sHfuX04820wR0ehyjWZQto/edit?usp=sharing"

[mysql]
host = "localhost"
port = 3306
database = "lessons"
user = "newuser"
password = "password"
